"use client"

import { AlertTriangle, CalendarDays, PackageSearch } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useBoticaStore, categoryLabel } from "@/lib/botica-store"
import { formatMoney } from "@/lib/money"

export default function BoticaInventarioPage() { const { state, ready, stats } = useBoticaStore(); if (!ready) return <p>Cargando inventario...</p>; return <div className="space-y-6"><div className="border-b pb-4"><h1 className="text-2xl font-bold">Inventario, lotes y vencimientos</h1><p className="text-sm text-muted-foreground">Control de existencias y fechas críticas de medicamentos.</p></div><div className="grid gap-3 sm:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><PackageSearch className="size-4 text-emerald-600" />Productos</CardTitle></CardHeader><CardContent className="text-3xl font-black">{state.products.length}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle className="size-4 text-rose-600" />Stock bajo</CardTitle></CardHeader><CardContent className="text-3xl font-black text-rose-600">{stats.lowStock.length}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="size-4 text-amber-600" />Por vencer</CardTitle></CardHeader><CardContent className="text-3xl font-black text-amber-600">{stats.expiring.length}</CardContent></Card></div><div className="overflow-hidden rounded-xl border bg-card"><div className="grid grid-cols-7 gap-2 border-b bg-muted/40 px-4 py-3 text-xs font-bold text-muted-foreground"><span>Producto</span><span>Categoría</span><span>Lote</span><span>Vencimiento</span><span>Stock</span><span>Precio</span><span>Estado</span></div>{state.products.map((product) => <div key={product.id} className="grid grid-cols-7 gap-2 border-b px-4 py-3 text-xs last:border-0"><span><strong className="block">{product.name}</strong><span className="text-muted-foreground">{product.activeIngredient}</span></span><span>{categoryLabel(product.category)}</span><span className="font-mono">{product.lot}</span><span>{product.expiresAt}</span><span className={product.stock <= product.minStock ? "font-bold text-rose-600" : ""}>{product.stock}</span><span className="font-bold">{formatMoney(product.salePrice)}</span><span>{product.stock <= product.minStock ? <Badge className="bg-rose-100 text-rose-800">Reponer</Badge> : product.expiresAt <= "2026-12-31" ? <Badge className="bg-amber-100 text-amber-800">Revisar</Badge> : <Badge className="bg-emerald-100 text-emerald-800">OK</Badge>}</span></div>)}</div></div> }
