"use client"

import { useState } from "react"
import { CalendarDays, CheckCircle2, Clock3, UserRound } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { useSpaStore, appointmentStatusLabel } from "@/lib/spa-store"
import type { SpaAppointmentStatus } from "@/lib/spa-types"
import { todayISO } from "@/lib/money"

export default function SpaAgendaPage() { const { state, ready, updateAppointment } = useSpaStore(); const [selectedId, setSelectedId] = useState<string | null>(null); if (!ready) return <p>Cargando agenda...</p>; const selected = state.appointments.find((item) => item.id === selectedId); const statuses: SpaAppointmentStatus[] = ["reservada", "confirmada", "en_atencion", "lista_para_cobro", "atendida", "cancelada", "no_asistio"]; return <div className="space-y-6"><div className="border-b pb-4"><p className="text-sm text-muted-foreground">Agenda del {todayISO()}</p><h1 className="text-2xl font-bold">Citas y cabinas</h1><p className="text-sm text-muted-foreground">Actualiza el estado de cada tratamiento en tiempo real.</p></div><div className="grid gap-4">{state.appointments.map((appointment) => { const client = state.clients.find((item) => item.id === appointment.clientId); const service = state.services.find((item) => item.id === appointment.serviceId); return <Card key={appointment.id}><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="flex items-center gap-2"><Clock3 className="size-4 text-rose-600" />{appointment.time} · {client?.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{service?.name} · {appointment.room} · {appointment.professional}</p></div><Badge variant={appointment.status === "en_atencion" ? "default" : "outline"}>{appointmentStatusLabel(appointment.status)}</Badge></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-1 text-xs text-muted-foreground"><UserRound className="size-3.5" />{client?.phone} · Adelanto: S/ {appointment.amountPaid.toFixed(2)}</p><Button size="sm" onClick={() => setSelectedId(appointment.id)}><CalendarDays className="mr-1 size-3.5" />Cambiar estado</Button></CardContent></Card> })}</div><Dialog open={!!selected} onOpenChange={(open) => !open && setSelectedId(null)}><DialogContent><DialogHeader><DialogTitle>Actualizar cita</DialogTitle></DialogHeader>{selected && <div className="space-y-3"><Label>Estado de atención</Label><select value={selected.status} onChange={(event) => updateAppointment(selected.id, { status: event.target.value as SpaAppointmentStatus })} className="h-9 w-full rounded-lg border bg-background px-3 text-sm">{statuses.map((status) => <option key={status} value={status}>{appointmentStatusLabel(status)}</option>)}</select></div>}<DialogFooter><Button onClick={() => setSelectedId(null)}><CheckCircle2 className="mr-1 size-4" />Listo</Button></DialogFooter></DialogContent></Dialog></div> }
