"use client"

import Link from "next/link"
import { Activity, AlertTriangle, Headphones, PhoneCall } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle } from "@/components/ui/card"
import { useCallCenterStore, statusLabel } from "@/lib/callcenter-store"
import { todayISO } from "@/lib/money"

export default function CallCenterPage() {
  const { state, ready, stats, reset } = useCallCenterStore()
  if (!ready) return <p className="text-sm text-muted-foreground">Iniciando central de atención...</p>
  const pendingCases = state.cases.filter((item) => item.status !== "resuelto").slice(0, 4)
  return <div className="space-y-6">
    <div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Badge className="bg-cyan-100 text-cyan-900"><Headphones className="mr-1 size-3" /> Operación en vivo</Badge><span className="text-xs text-muted-foreground">{todayISO()}</span></div><h1 className="mt-1.5 text-2xl font-bold">Panel de trabajo</h1><p className="text-sm text-muted-foreground">Organiza la cola, registra cada contacto y programa el siguiente paso.</p></div><Button variant="outline" size="sm" onClick={reset}>Restaurar datos</Button></div>
    <div className="grid gap-3 sm:grid-cols-4"><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Casos pendientes</p><CardTitle className="text-2xl text-cyan-700">{stats.pending}</CardTitle><p className="text-xs text-muted-foreground">En la cola de atención</p></CardHeader></Card><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Prioridad alta</p><CardTitle className="text-2xl text-rose-600">{stats.highPriority}</CardTitle><p className="text-xs text-muted-foreground">Requieren atención hoy</p></CardHeader></Card><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Contactos hoy</p><CardTitle className="text-2xl text-emerald-600">{stats.contactedToday}</CardTitle><p className="text-xs text-muted-foreground">Interacciones registradas</p></CardHeader></Card><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Casos resueltos</p><CardTitle className="text-2xl">{stats.resolved}</CardTitle><p className="text-xs text-muted-foreground">Cerrados por el equipo</p></CardHeader></Card></div>
    <div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><PhoneCall className="size-4 text-cyan-700" />Siguiente atención</CardTitle><Link href="/callcenter/cola"><Button size="sm">Ver cola completa</Button></Link></CardHeader><div className="divide-y">{pendingCases.map((item) => { const client = state.clients.find((clientItem) => clientItem.id === item.clientId); return <div key={item.id} className="flex flex-wrap items-center gap-3 px-6 py-3"><div className="min-w-0 flex-1"><p className="font-semibold">{client?.name}</p><p className="text-xs text-muted-foreground">{item.subject} · {item.assignedTo}</p></div><Badge variant={item.priority === "alta" ? "destructive" : "outline"}>{item.priority}</Badge><span className="text-xs text-muted-foreground">{statusLabel(item.status)}</span></div> })}</div></Card><div className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Activity className="size-4 text-cyan-700" />Equipo conectado</CardTitle></CardHeader><div className="space-y-2 px-6 pb-5">{state.agents.map((agent, index) => <div key={agent} className="flex items-center justify-between text-sm"><span>{agent}</span><span className="flex items-center gap-1 text-xs text-emerald-700"><span className="size-2 rounded-full bg-emerald-500" />{index === 0 ? "En llamada" : "Disponible"}</span></div>)}</div></Card><div className="rounded-xl border border-amber-300 bg-amber-50 p-4"><div className="flex gap-2"><AlertTriangle className="size-5 text-amber-700" /><div><p className="font-semibold text-amber-950">Enfoque del turno</p><p className="text-sm text-amber-900">Atiende primero los casos de prioridad alta y registra siempre la próxima acción.</p></div></div></div></div></div>
  </div>
}
