"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { CheckCircle2, Coins, CreditCard, Minus, Plus, Scan, Search, ShoppingCart, Trash2 } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useBoticaStore } from "@/lib/botica-store"
import type { BoticaProduct, BoticaSaleItem } from "@/lib/botica-types"
import { formatMoney, todayISO } from "@/lib/money"

export default function BoticaPage() {
  const { state, ready, stats, findByBarcode, registerSale, reset } = useBoticaStore()
  const [cart, setCart] = useState<BoticaSaleItem[]>([])
  const [barcode, setBarcode] = useState("")
  const [query, setQuery] = useState("")
  const [paymentOpen, setPaymentOpen] = useState(false)
  const [paid, setPaid] = useState("")
  const [message, setMessage] = useState("")
  const barcodeRef = useRef<HTMLInputElement>(null)
  const total = cart.reduce((sum, item) => sum + item.subtotal, 0)
  const change = Math.max(0, (Number(paid) || 0) - total)

  const addProduct = useCallback((product: BoticaProduct) => {
    setCart((current) => { const existing = current.find((item) => item.productId === product.id); if (existing) return current.map((item) => item.productId === product.id ? { ...item, qty: item.qty + 1, subtotal: (item.qty + 1) * item.unitPrice } : item); return [...current, { productId: product.id, barcode: product.barcode, name: product.name, presentation: product.presentation, qty: 1, unitPrice: product.salePrice, subtotal: product.salePrice }] })
  }, [])
  useEffect(() => { barcodeRef.current?.focus() }, [cart.length])
  function scan(event: React.KeyboardEvent<HTMLInputElement>) { if (event.key !== "Enter") return; const product = findByBarcode(barcode.trim()); setMessage(product ? `Agregado: ${product.name}` : `Código no encontrado: ${barcode}`); if (product) addProduct(product); setBarcode(""); setTimeout(() => setMessage(""), 2400) }
  function updateQty(id: string, delta: number) { setCart((current) => current.map((item) => item.productId === id ? { ...item, qty: item.qty + delta, subtotal: (item.qty + delta) * item.unitPrice } : item).filter((item) => item.qty > 0)) }
  function confirmSale() { if (!cart.length || Number(paid) < total) return; registerSale({ items: cart, amountPaid: Number(paid), paymentMethod: "efectivo" }); setCart([]); setPaid(""); setPaymentOpen(false); setMessage("Venta registrada correctamente"); setTimeout(() => setMessage(""), 2400) }
  const filtered = query.length > 1 ? state.products.filter((product) => `${product.name} ${product.activeIngredient} ${product.barcode}`.toLowerCase().includes(query.toLowerCase())) : []
  if (!ready) return <p className="text-sm text-muted-foreground">Iniciando caja de botica...</p>
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Badge className="bg-emerald-100 text-emerald-800"><Scan className="mr-1 size-3" /> POS Botica</Badge><span className="text-xs text-muted-foreground">{todayISO()}</span></div><h1 className="mt-1.5 text-2xl font-bold">Caja de mostrador</h1><p className="text-sm text-muted-foreground">Medicamentos, productos de cuidado y ventas rápidas.</p></div><Button variant="outline" size="sm" onClick={reset}>Restaurar datos</Button></div>
    <div className="grid gap-3 sm:grid-cols-4"><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Ventas de hoy</p><CardTitle className="text-2xl text-emerald-600">{formatMoney(stats.totalToday)}</CardTitle><p className="text-xs text-muted-foreground">{stats.transactions} transacciones</p></CardHeader></Card><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Productos</p><CardTitle className="text-2xl">{state.products.length}</CardTitle><p className="text-xs text-muted-foreground">Catálogo activo</p></CardHeader></Card><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Stock bajo</p><CardTitle className="text-2xl text-rose-600">{stats.lowStock.length}</CardTitle><p className="text-xs text-muted-foreground">Requieren reposición</p></CardHeader></Card><Card size="sm"><CardHeader><p className="text-xs text-muted-foreground">Por vencer</p><CardTitle className="text-2xl text-amber-600">{stats.expiring.length}</CardTitle><p className="text-xs text-muted-foreground">Antes de fin de año</p></CardHeader></Card></div>
    {message && <div className="flex items-center gap-2 rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-sm text-emerald-800"><CheckCircle2 className="size-4" />{message}</div>}
    <div className="grid gap-6 lg:grid-cols-5"><div className="space-y-4 lg:col-span-2"><div className="space-y-3 rounded-xl border-2 border-dashed border-emerald-400/50 bg-emerald-50/40 p-4"><div className="flex items-center gap-2"><Scan className="size-5 text-emerald-600" /><div><p className="font-bold">Escanear producto</p><p className="text-xs text-muted-foreground">Código de barras y Enter</p></div></div><Input ref={barcodeRef} value={barcode} onChange={(event) => setBarcode(event.target.value)} onKeyDown={scan} placeholder="7751234560012" className="font-mono" /></div><div className="space-y-2"><Label>Buscar por nombre o principio activo</Label><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ej. paracetamol, Panadol..." /></div>{filtered.length > 0 && <div className="divide-y overflow-hidden rounded-xl border bg-card">{filtered.map((product) => <button key={product.id} onClick={() => { addProduct(product); setQuery("") }} className="flex w-full items-center justify-between px-3 py-2 text-left hover:bg-muted"><span><span className="block text-xs font-semibold">{product.name}</span><span className="text-[11px] text-muted-foreground">{product.activeIngredient} · Stock {product.stock}</span></span><span className="font-bold text-emerald-700">{formatMoney(product.salePrice)}</span></button>)}</div>}</div><div className="space-y-2"><Label className="text-xs uppercase text-muted-foreground">Acceso rápido</Label><div className="grid grid-cols-2 gap-2">{state.products.slice(0, 6).map((product) => <button key={product.id} onClick={() => addProduct(product)} className="rounded-lg border bg-card p-2 text-left text-xs hover:bg-muted"><p className="truncate font-semibold">{product.name}</p><p className="text-muted-foreground">{product.presentation}</p><p className="mt-1 font-bold text-emerald-700">{formatMoney(product.salePrice)}</p></button>)}</div></div></div>
    <div className="space-y-4 lg:col-span-3"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><ShoppingCart className="size-4 text-emerald-600" />Ticket actual {cart.length > 0 && <Badge>{cart.length}</Badge>}</h2>{cart.length > 0 && <Button variant="ghost" size="xs" onClick={() => setCart([])} className="text-rose-600"><Trash2 className="mr-1 size-3" />Vaciar</Button>}</div><div className="min-h-[240px] overflow-hidden rounded-xl border bg-card">{cart.length === 0 ? <div className="flex flex-col items-center justify-center gap-2 py-16 text-muted-foreground"><ShoppingCart className="size-10 opacity-30" /><p className="text-sm">El ticket está vacío</p></div> : <div className="divide-y">{cart.map((item) => <div key={item.productId} className="flex items-center gap-3 px-4 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.name}</p><p className="text-xs text-muted-foreground">{item.presentation} · {formatMoney(item.unitPrice)}</p></div><div className="flex items-center gap-1"><button className="flex size-6 items-center justify-center rounded border" onClick={() => updateQty(item.productId, -1)}><Minus className="size-3" /></button><span className="w-7 text-center text-sm font-bold">{item.qty}</span><button className="flex size-6 items-center justify-center rounded border" onClick={() => updateQty(item.productId, 1)}><Plus className="size-3" /></button></div><span className="w-16 text-right text-sm font-bold">{formatMoney(item.subtotal)}</span></div>)}</div>}</div><div className="space-y-3 rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><span className="font-semibold text-muted-foreground">TOTAL A COBRAR</span><span className="text-3xl font-black">{formatMoney(total)}</span></div><Button className="h-12 w-full bg-emerald-600 text-base font-bold hover:bg-emerald-700" disabled={!cart.length} onClick={() => { setPaid(total.toFixed(2)); setPaymentOpen(true) }}><Coins className="mr-2 size-5" />Cobrar venta</Button></div></div></div>
    <Dialog open={paymentOpen} onOpenChange={setPaymentOpen}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2"><CreditCard className="size-5 text-emerald-600" />Cobrar venta · {formatMoney(total)}</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid grid-cols-3 gap-2"><button className="rounded-lg border bg-emerald-100 p-2 text-xs font-bold text-emerald-900">💵 Efectivo</button><button onClick={() => registerSale({ items: cart, amountPaid: total, paymentMethod: "yape_plin", gateway: "Mercado Pago" })} className="rounded-lg border p-2 text-xs font-semibold hover:bg-muted">📱 Yape / Plin</button><button onClick={() => registerSale({ items: cart, amountPaid: total, paymentMethod: "tarjeta", gateway: "POS" })} className="rounded-lg border p-2 text-xs font-semibold hover:bg-muted">💳 Tarjeta</button></div><div><Label htmlFor="paid">Monto recibido (S/)</Label><Input id="paid" type="number" min={total} value={paid} onChange={(event) => setPaid(event.target.value)} className="mt-1 text-lg font-bold" /></div><div className="flex items-center justify-between rounded-lg border bg-muted/30 p-3"><span className="text-sm">Vuelto</span><strong className="text-xl text-emerald-700">{formatMoney(change)}</strong></div></div><DialogFooter><Button variant="outline" onClick={() => setPaymentOpen(false)}>Cancelar</Button><Button className="bg-emerald-600 text-white" disabled={Number(paid) < total} onClick={confirmSale}>Confirmar cobro</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
